#- hosts: "{{ TARGET_HOSTS }}"
- hosts: "localhost"
  tasks:
    - name: make docker image
      shell: |
        cd /home/drno/IdeaProjects/inclouds/msk_scope
        docker build -t drnoreg/inclouds_msk_scope:0.1 ./
        docker save drnoreg/inclouds_msk_scope:0.1 > /opt/docker/images/inclouds_msk_scope.tar
        scp -P 12345 /opt/docker/images/inclouds_msk_scope.tar ansible@89.22.182.135:/opt/docker/images
#        docker push drnoreg/inclouds_main_app:0.1
- hosts: "89.22.182.135"
  tasks:
    - name: check docker image
      shell: docker ps -a
      register: dockerps
      tags: dockerps
    - debug: msg="{{dockerps.stdout}}"
    - name: stop and delete docker container
      shell: |
        docker stop inclouds_msk_scope
        docker rm inclouds_msk_scope
        docker rmi drnoreg/inclouds_msk_scope:0.1
        docker load -i /opt/docker/images/inclouds_msk_scope.tar
#        docker pull drnoreg/inclouds_main_app:0.1
    - name: pull and start docker container
      shell: docker run --net inclouds_network --name=inclouds_msk_scope -d -p 8228:8228 -d -v /opt/docker/sqlite_inclouds:/msk_scope/scope/db -v /opt/docker/msk_scope/files:/msk_scope/scope/files -v /opt/docker/msk_scope/configs:/msk_scope/scope/configs drnoreg/inclouds_msk_scope:0.1
    - name: check docker image
      shell: docker ps -a
      register: dockerps
      tags: dockerps
    - debug: msg="{{dockerps.stdout}}"

#- host: "localhost"
#  tasks:
#    - name: check URL
#      shell: Test is OK
#      when: curl https://inclouds.bizml.ru | grep "<td>/main</td>" == "<td>/main</td>"
#      stat: curl https://inclouds.bizml.ru | grep "<td>/main</td>"
#      register: st
#    - include: "if st.stat.exists 'echo '"
